"""Shared chronology loading utilities for MCP servers.

Provides cached access to the unified chronology JSON generated by
`src/dev_tools/docs/generate_chronological_index.py` plus optional diff
(delta) JSON. This is read-only; only the IDS server triggers regeneration.

Functions:
    load_chronology(path: Optional[str], cache: bool) -> dict
    query_chronology(data: dict, kind: str, limit: int, reverse: bool) -> list
    load_delta(path: Optional[str]) -> dict | None

Chronology JSON schema (subset):
{
  "generated": "2025-08-15T12:34:56Z",
  "ordering": "forward|reverse",
  "documents": [ {"path","title","created","updated","hash","type"}, ... ],
  "source": [...],
  "mcp": [...],
  "root": [...]
}

Delta JSON schema (if generated with --delta):
{
  "generated": "...",
  "added": [ entry, ... ],
  "removed": [ entry, ... ],
  "changed": [ { "before": entry, "after": entry }, ... ],
  "counts": {"added": int, "removed": int, "changed": int}
}
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

# Default locations relative to project root
DEFAULT_CHRONOLOGY_PATH = Path('docs/timelines/chronology_index.json')
DEFAULT_DELTA_PATH = Path('docs/timelines/chronology_index_diff.json')
_DATE_FMT = '%B %d, %Y'

# Simple module-level caches (safe for short-lived MCP processes)
_cache_data: dict[str, Any] | None = None
_cache_mtime: float | None = None
_cache_path: Path | None = None


def load_chronology(path: str | None = None, cache: bool = True) -> dict[str, Any]:
    """Load chronology JSON with optional mtime-based caching.

    Args:
        path: Optional explicit path; defaults to DEFAULT_CHRONOLOGY_PATH.
        cache: If True, reuse cached data when unchanged.
    Returns:
        Parsed JSON dict (empty structure if missing or parse error).
    """
    global _cache_data, _cache_mtime, _cache_path
    chrono_path = Path(path) if path else DEFAULT_CHRONOLOGY_PATH
    if cache and _cache_data is not None and _cache_path == chrono_path:
        try:
            current_mtime = chrono_path.stat().st_mtime
            if _cache_mtime == current_mtime:
                return _cache_data
        except FileNotFoundError:
            return _cache_data  # keep last known
    try:
        text = chrono_path.read_text(encoding='utf-8')
        data = json.loads(text)
    except Exception:
        data = {"documents": [], "source": [], "mcp": [], "root": []}
    try:
        _cache_mtime = chrono_path.stat().st_mtime
    except Exception:
        _cache_mtime = None
    _cache_data = data
    _cache_path = chrono_path
    return data


def query_chronology(data: dict[str, Any], kind: str = 'all', limit: int = 50, reverse: bool = False) -> list[dict[str, Any]]:
    """Return flattened subset of chronology entries.

    kind: one of all|docs|source|mcp|root
    limit: max number of results (None/0 for all)
    reverse: newest-first ordering by created date
    """
    pools: list[dict[str, Any]] = []
    if kind in ('all', 'docs'):
        pools.extend(data.get('documents', []))
    if kind in ('all', 'source'):
        pools.extend(data.get('source', []))
    if kind in ('all', 'mcp'):
        pools.extend(data.get('mcp', []))
    if kind in ('all', 'root'):
        pools.extend(data.get('root', []))

    def parse_created(e):
        try:
            return datetime.strptime(e.get('created', ''), _DATE_FMT)
        except Exception:
            # push unknowns to end (or start if reverse)
            return datetime.min if reverse else datetime.max

    pools.sort(key=parse_created, reverse=reverse)
    if limit:
        pools = pools[:limit]
    return pools


def load_delta(path: str | None = None) -> dict[str, Any] | None:
    """Load delta (diff) JSON if present."""
    delta_path = Path(path) if path else DEFAULT_DELTA_PATH
    if not delta_path.exists():
        return None
    try:
        return json.loads(delta_path.read_text(encoding='utf-8'))
    except Exception:
        return None


__all__ = [
    'DEFAULT_CHRONOLOGY_PATH',
    'DEFAULT_DELTA_PATH',
    'load_chronology',
    'load_delta',
    'query_chronology'
]
