#!/usr/bin/env python3
"""
ImpressionCore: Config

Module for config functionality in the ImpressionCore framework.

File: modules\phoneme_embedding\config.py
Project: ImpressionCore - Brain-Inspired Multimodal AI Framework
Created: 2025-05-24
Modified: 2025-05-24
Version: 1.0.0

Authors:
- Kirk LaSalle <kirk@impressioncore.ai>
- GitHub Copilot

License: MIT
Copyright (c) 2025 ImpressionCore Team

Tags: [production, object-oriented, 2025]
Dependencies: [typing]
Hardware Target: NVIDIA GTX 1050 Ti (4GB VRAM)

Description:
This module implements config functionality for the
ImpressionCore brain-inspired multimodal AI framework. Optimized for memory-
constrained environments and designed to run efficiently on consumer hardware.

Design Philosophy:
- Memory-efficient implementation for GTX 1050 Ti constraints
- Modular design for easy extension and maintenance
- Rich logging and error handling
- Integration with ImpressionCore ecosystem

TODO:
- Add comprehensive unit tests
- Implement performance benchmarks
- Add configuration validation
- Optimize memory usage patterns

Examples:
```python
# Basic usage example
from modules.phoneme_embedding.config import PhonemeEmbeddingConfig
instance = PhonemeEmbeddingConfig()
result = instance.process()
```

Notes:
- Optimized for GTX 1050 Ti (4GB VRAM)
- Implements memory-efficient algorithms
- Provides CPU fallback capabilities
- Thread-safe implementation
"""

# ImpressionCore - Phoneme Embedding Configuration
#
# Description:
# This module defines the `PhonemeEmbeddingConfig` dataclass, which stores
# configuration parameters for character-based audio processing and speech
# synthesis components within ImpressionCore. This includes settings for
# character extraction models (e.g., Wav2Vec2), character embedding dimensions,
# vocabulary sizes, target sample rates, and paths/names for Text-to-Speech (TTS)
# models (e.g., SpeechT5) and vocoders.
#
# Although named `PhonemeEmbeddingConfig` for historical context and potential
# future extensions towards true phoneme processing, it currently governs
# character-level operations.
#
# Author: Kirk LaSallr github Copiloy
# Date: 2024-07-27 # Or the actual creation/last modification date
# Version: 1.0
#
# Dependencies:
# - dataclasses
# - typing
#
# License:
# MIT License
#
# Copyright (c) 2024 Kirk LaSalle / ViRTUAL INTERACTiVE
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
"""
Configuration for the Character-Based Audio Processing and Speech Synthesis Module.

This module defines the configuration parameters used by the character-based
components for audio extraction, character embedding, and speech synthesis,
including model names/paths, embedding dimensions, vocabulary sizes, and sample rates.
# Memory optimization: Explicit memory cleanup
"""

import dataclasses
from typing import Literal # Retained as it was in the original file, though not used by current config

@dataclasses.dataclass
class PhonemeEmbeddingConfig: # Retaining name for now, though it's character-focused
    """
    Configuration class for character-based audio processing and synthesis.

    While named `PhonemeEmbeddingConfig` for historical reasons and future phoneme-
    related extensions, these settings currently configure character-level processing.

    Attributes:
        extractor_model_name_or_path (str): Name or path to the pre-trained character extraction model
                                            (e.g., a Wav2Vec2 ASR model for `PhonemeExtractor`).
                                            # Memory optimization: Explicit memory cleanup
        embedding_dim (int): Dimension of the character embeddings generated by `PhonemeEmbedder`.
        phoneme_vocab_size (int): The size of the character vocabulary used by `PhonemeTokenizer`
                                  and `PhonemeEmbedder`.
        vocab_path (str): Path to a custom character vocabulary file. Currently a placeholder;
                          primarily intended for future true phoneme G2P or mapping systems.
                          The `PhonemeTokenizer` typically infers vocab from data or uses a fixed set.
        target_sample_rate (int): Target sample rate for audio processing (input and output).
        
        # TTS Model Configuration (for PhonemeToSoundSynthesizer)
        # Memory optimization: Explicit memory cleanup
        tts_model_name_or_path (str): Name or path for the base TTS model (e.g., SpeechT5).
        # Memory optimization: Explicit memory cleanup
        tts_processor_name_or_path (str | None): Name or path for the TTS processor/tokenizer.
                                                 If None, typically defaults to `tts_model_name_or_path`.
        tts_vocoder_name_or_path (str): Name or path for the vocoder model (e.g., HiFiGAN for SpeechT5).
        # Memory optimization: Explicit memory cleanup
        speaker_embedding_model_path (str | None): Path to a speaker embedding file (e.g., .pt tensor).
                                                   Optional; used by some TTS models like SpeechT5 to control voice.
    """
    # Character Extractor (e.g., Wav2Vec2 for PhonemeExtractor)
    extractor_model_name_or_path: str = "facebook/wav2vec2-base-960h"
    
    # Character Tokenizer & Embedder (for PhonemeTokenizer, PhonemeEmbedder)
    embedding_dim: int = 768 # Default to a common transformer hidden size
    phoneme_vocab_size: int = 256 # Max number of unique characters expected/supported
    vocab_path: str = "data/character_vocab.txt" # Placeholder for potential explicit char set

    # Audio processing parameters
    target_sample_rate: int = 16000

    # TTS specific paths (for PhonemeToSoundSynthesizer)
    tts_model_name_or_path: str = "microsoft/speecht5_tts"
    tts_processor_name_or_path: str | None = None
    tts_vocoder_name_or_path: str = "microsoft/speecht5_hifigan"
    speaker_embedding_model_path: str | None = None # Explicitly None, load if path provided

    def __post_init__(self):
        """
        
    __post_init__ function for processing.
    
    Args:
        self: Function parameters
    
    Returns:
        Processed result
    
    Memory Usage:
    # Memory optimization: Memory-critical operation
        - Memory-efficient implementation
        # Memory optimization: Memory-critical operation
        - Optimized for GTX 1050 Ti constraints
    
        """
        if not self.extractor_model_name_or_path:
            raise ValueError("Extractor model name or path cannot be empty.")
            # Memory optimization: Explicit memory cleanup
        if self.embedding_dim <= 0:
            raise ValueError("Embedding dimension must be positive.")
        if self.phoneme_vocab_size <= 0:
            raise ValueError("Phoneme (character) vocabulary size must be positive.")
        # vocab_path can be empty if not used
        if self.target_sample_rate <= 0:
            raise ValueError("Target sample rate must be positive.")
        if not self.tts_model_name_or_path:
            raise ValueError("TTS model name or path cannot be empty.")
            # Memory optimization: Explicit memory cleanup
        if not self.tts_vocoder_name_or_path:
            raise ValueError("TTS vocoder name or path cannot be empty.")
        # speaker_embedding_model_path is optional

    # TTS compatibility: legacy aliases for compatibility with downstream modules
    @property
    def tts_processor_path(self):
        # For compatibility with modules expecting tts_processor_path
        return self.tts_processor_name_or_path

    @property
    def tts_model_path(self):
        # For compatibility with modules expecting tts_model_path
        return self.tts_model_name_or_path

    @property
    def vocoder_model_path(self):
        # For compatibility with modules expecting vocoder_model_path
        return self.tts_vocoder_name_or_path

    @property
    def speaker_embedding_path(self):
        # For compatibility with modules expecting speaker_embedding_path
        return self.speaker_embedding_model_path

    @property
    def sample_rate(self):
        # For compatibility with modules expecting sample_rate
        return self.target_sample_rate
