#!/usr/bin/env python3
"""Merge multiple teacher response JSON dumps into a single dataset.

Usage example:
    python -m src.training.distillation.processing.combine_teacher_runs \
        --inputs a.json b.json c.json \
        --out merged.json

The script preserves the input schema expected by Colossus distillation:
{
  "generation_timestamp": "...",
  "teacher_models": ["modelA", ...],
  "examples": [
      {
          "prompt": "...",
          "teacher_responses": {
              "modelA": "...",
              "modelB": "..."
          }
      }
  ]
}
"""
from __future__ import annotations

import argparse
import json
from collections.abc import Mapping
from datetime import datetime, timezone
from pathlib import Path


def _load_examples(path: Path) -> Mapping[str, Mapping[str, str]]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"Failed to load teacher dataset {path}: {exc}") from exc
    results: dict[str, dict[str, str]] = {}
    for entry in payload.get("examples", []):
        prompt = entry.get("prompt")
        responses = entry.get("teacher_responses")
        if not isinstance(prompt, str) or not prompt.strip():
            continue
        if not isinstance(responses, Mapping):
            continue
        store = results.setdefault(prompt, {})
        for teacher, text in responses.items():
            if isinstance(teacher, str) and isinstance(text, str) and text.strip():
                store[teacher] = text
    return results


def merge_teacher_runs(inputs: list[Path]) -> dict[str, dict[str, str]]:
    merged: dict[str, dict[str, str]] = {}
    for source in inputs:
        examples = _load_examples(source)
        for prompt, teacher_map in examples.items():
            store = merged.setdefault(prompt, {})
            for teacher, response in teacher_map.items():
                store[teacher] = response
    return merged


def build_payload(merged: Mapping[str, Mapping[str, str]]) -> dict[str, object]:
    teacher_models = sorted({teacher for responses in merged.values() for teacher in responses})
    examples = []
    for prompt in sorted(merged.keys()):
        examples.append(
            {
                "prompt": prompt,
                "teacher_responses": dict(sorted(merged[prompt].items())),
            }
        )
    return {
        "generation_timestamp": datetime.now(timezone.utc).isoformat(),
        "teacher_models": teacher_models,
        "total_examples": len(examples),
        "examples": examples,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Combine multiple teacher response JSON files into one dataset")
    parser.add_argument("--inputs", nargs="+", type=Path, help="Paths to teacher JSON files generated by Ollama pipeline")
    parser.add_argument("--out", type=Path, required=True, help="Destination JSON path for merged dataset")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    inputs: list[Path] = [path.expanduser() for path in args.inputs]
    if not inputs:
        raise SystemExit("No input teacher datasets provided")
    merged = merge_teacher_runs(inputs)
    if not merged:
        raise SystemExit("Merged dataset has no overlapping teacher responses")
    payload = build_payload(merged)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[ok] Wrote merged teacher dataset with {payload['total_examples']} prompts -> {args.out}")


if __name__ == "__main__":  # pragma: no cover
    main()
