
⚠️ ARCHIVED FILE
This file has been archived for historical, compatibility, or deprecation reasons. Do not modify or use in active development.

#!/usr/bin/env python3
"""
!/usr/bin/env python3

**Created:** October-15-2024
**Updated:** August-04-2025
**Author:** ImpressionCore Team
**Tags:** #api #deployment #python #source_code #src/scripts/utilities/setup_f_models_structure.py #testing #training
**Category:** Source Code
**Status:** Deprecated
"""



import os
import json
from pathlib import Path
from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

class FModelsStructureSetup:
    """Setup new F:\models directory structure"""

    def __init__(self):
        self.console = Console()
        self.base_path = Path("F:/models")

        # Define the new directory structure
        self.directory_structure = {
            "checkpoints": {
                "description": "Production model checkpoints and best quality models",
                "subdirs": ["best_quality", "production", "backup"]
            },
            "training": {
                "description": "Active training models and checkpoint progression",
                "subdirs": ["active", "epochs", "experiments", "logs"]
            },
            "distillation": {
                "description": "Knowledge distillation results and enhanced models",
                "subdirs": ["ollama_progressive", "remote_api", "enhanced_models", "curriculum"]
            },
            "deployment": {
                "description": "Deployment-ready models and configurations",
                "subdirs": ["production", "testing", "configs"]
            },
            "archives": {
                "description": "Historical models and legacy backups",
                "subdirs": ["legacy", "experiments", "deprecated"]
            },
            "infrastructure": {
                "description": "Model infrastructure, scripts, and utilities",
                "subdirs": ["scripts", "configs", "utilities", "monitoring"]
            }
        }

    def create_directory_structure(self):
        """Create the complete F:\models directory structure"""
        self.console.print(Panel("🏗️ Setting Up F:\\models Directory Structure", style="blue"))

        created_dirs = []

        # Create base directory
        self.base_path.mkdir(parents=True, exist_ok=True)
        created_dirs.append(str(self.base_path))

        # Create main directories and subdirectories
        for main_dir, config in self.directory_structure.items():
            main_path = self.base_path / main_dir
            main_path.mkdir(exist_ok=True)
            created_dirs.append(str(main_path))

            # Create subdirectories
            for subdir in config["subdirs"]:
                sub_path = main_path / subdir
                sub_path.mkdir(exist_ok=True)
                created_dirs.append(str(sub_path))

            # Create README.md for each main directory
            readme_path = main_path / "README.md"
            with open(readme_path, 'w', encoding='utf-8') as f:
                f.write(f"""# {main_dir.title()} Directory

**Purpose:** {config['description']}

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Subdirectories:

""")
                for subdir in config["subdirs"]:
                    f.write(f"- `{subdir}/` - {subdir.replace('_', ' ').title()} storage\n")

                f.write(f"""
## Usage Guidelines:

- All models in this directory follow ImpressionCore naming conventions
- Maintain timestamp-based versioning for checkpoints
- Use descriptive names for production models
- Archive old models to appropriate subdirectories

---
*Generated by ImpressionCore F:\\models Structure Setup*
""")

        return created_dirs

    def create_migration_script(self):
        """Create script to migrate existing models from F:\data to F:\models"""
        migration_script = self.base_path / "infrastructure" / "scripts" / "migrate_from_f_data.py"
        migration_script.parent.mkdir(parents=True, exist_ok=True)

        with open(migration_script, 'w', encoding='utf-8') as f:
            f.write('''#!/usr/bin/env python3
"""
Migration Script: F:\\data to F:\\models
=====================================

Migrates existing models from F:\\data structure to new F:\\models structure.
"""

import shutil
from pathlib import Path
from rich.console import Console

def migrate_models():
    console = Console()

    # Migration mappings
    migrations = {
        "F:/data/embeddings/b3_training/checkpoints/*.pth": "F:/models/checkpoints/legacy/",
        "F:/data/distillation/ollama_progressive/": "F:/models/distillation/ollama_progressive/",
        "F:/data/distillation/remote_api/": "F:/models/distillation/remote_api/",
        "F:/data/training/": "F:/models/training/legacy/"
    }

    console.print("🚀 Starting F:\\data to F:\\models migration...")

    # Best quality model priority migration
    best_quality_source = "F:/data/embeddings/b3_training/checkpoints/b3_best_quality_model_20250802_124801.pth"
    best_quality_dest = "F:/models/checkpoints/best_quality/"

    if Path(best_quality_source).exists():
        shutil.copy2(best_quality_source, best_quality_dest)
        console.print(f"✅ Migrated best quality model to {best_quality_dest}")

    console.print("✅ Migration completed!")

if __name__ == "__main__":
    migrate_models()
''')

        return str(migration_script)

    def update_distillation_configs(self):
        """Create updated configurations for distillation systems"""
        config_path = self.base_path / "infrastructure" / "configs" / "distillation_config.json"
        config_path.parent.mkdir(parents=True, exist_ok=True)

        distillation_config = {
            "version": "2.0.0",
            "updated": datetime.now().isoformat(),
            "base_paths": {
                "models_root": "F:/models",
                "checkpoints": "F:/models/checkpoints",
                "training": "F:/models/training",
                "distillation": "F:/models/distillation",
                "deployment": "F:/models/deployment"
            },
            "ollama_progressive": {
                "output_dir": "F:/models/distillation/ollama_progressive",
                "checkpoint_dir": "F:/models/training/active",
                "enhanced_models_dir": "F:/models/distillation/enhanced_models"
            },
            "remote_api": {
                "output_dir": "F:/models/distillation/remote_api",
                "results_dir": "F:/models/distillation/remote_api/results",
                "enhanced_models_dir": "F:/models/distillation/enhanced_models"
            },
            "production": {
                "best_model_source": "F:/data/embeddings/b3_training/checkpoints/b3_best_quality_model_20250802_124801.pth",
                "production_deployment": "F:/models/deployment/production",
                "backup_location": "F:/models/checkpoints/backup"
            }
        }

        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(distillation_config, f, indent=2)

        return str(config_path)

    def display_structure_summary(self, created_dirs):
        """Display summary of created directory structure"""

        structure_table = Table(title="🏗️ F:\\models Directory Structure Created")
        structure_table.add_column("Directory", style="cyan")
        structure_table.add_column("Purpose", style="green")
        structure_table.add_column("Status", style="yellow")

        for main_dir, config in self.directory_structure.items():
            structure_table.add_row(
                f"F:\\models\\{main_dir}\\",
                config["description"],
                "✅ Created"
            )

        self.console.print(structure_table)

        self.console.print(Panel(
            f"🎯 F:\\models Structure Setup Complete!\n\n"
            f"📁 Total Directories Created: {len(created_dirs)}\n"
            f"🏗️ Structure: 6 main directories + subdirectories\n"
            f"📋 Configuration Files: Created\n"
            f"🔄 Migration Script: Available\n\n"
            f"Next Steps:\n"
            f"1. Run migration script to move best models/n"
            f"2. Update distillation systems to use F:\\models/n"
            f"3. Begin using F:\\models for all new models",
            title="Setup Summary",
            style="bold green"
        ))

    def run_setup(self):
        """Run complete F:\models structure setup"""
        self.console.print(Panel.fit(
            "🏗️ ImpressionCore F:\\models Structure Setup\n"
            "Establishing New Primary Model Storage Location",
            style="bold blue"
        ))

        # Create directory structure
        created_dirs = self.create_directory_structure()

        # Create migration script
        migration_script = self.create_migration_script()

        # Create distillation configurations
        config_file = self.update_distillation_configs()

        # Display summary
        self.display_structure_summary(created_dirs)

        return {
            "status": "success",
            "directories_created": len(created_dirs),
            "migration_script": migration_script,
            "config_file": config_file,
            "base_path": str(self.base_path)
        }

def main():
    """Main execution function"""
    setup = FModelsStructureSetup()
    results = setup.run_setup()

    if results["status"] == "success":
        print(f"\n✅ F:\\models structure setup completed successfully!")
        print(f"📁 Base location: {results['base_path']}")
        print(f"🔄 Migration script: {results['migration_script']}")
        print(f"⚙️ Configuration: {results['config_file']}")

if __name__ == "__main__":
    main()
